### ISSUE TITLE
error: cannot convert 'igraph_vector_t*' 

### ISSUE THREAD

**Issue by daniel-kelley** [daniel-kelley/wktcolor#10]
Fedora 38:
<pre>
g++ -Wall -Wextra -Werror -g  -MP -MMD -std=c++17   wktcolor.cpp  -lboost_program_options -ligraph -lOpenMeshCore -lColPack -lgeos_c -lwkt -o wktcolor
wktcolor.cpp: In member function 'void WktColor::create_contact_graph()':
wktcolor.cpp:303:29: error: cannot convert 'igraph_vector_t*' to 'const igraph_vector_int_t*'
  303 |     igraph_create(&contact, &edge, 0, IGRAPH_UNDIRECTED);
      |                             ^~~~~
      |                             |
      |                             igraph_vector_t*
In file included from /usr/include/igraph/igraph.h:58,
                 from wktcolor.cpp:34:
/usr/include/igraph/igraph_constructors.h:42:88: note:   initializing argument 2 of 'igraph_error_t igraph_create(igraph_t*, const igraph_vector_int_t*, igraph_integer_t, igraph_bool_t)'
   42 | t igraph_create(igraph_t *graph, const igraph_vector_int_t *edges, igraph_integer_t n,
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

</pre>

**Comment by szhorvat** [comment]
I just noticed this issue. This change is required for igraph 0.10. I wanted to point out that since igraph 0.10.4, there is another colouring heuristic available, which tends to produce more optimal colourings (i.e. using fewer colours). Please see https://igraph.org/c/html/latest/igraph-Coloring.html#igraph_coloring_greedy_t I thought you may be interested in this.

**Comment by daniel-kelley** [comment]
> I just noticed this issue. This change is required for igraph 0.10. I
> wanted to point out that since igraph 0.10.4, there is another colouring
> heuristic available, which tends to produce more optimal colourings (i.e.
> using fewer colours). Please see
> https://igraph.org/c/html/latest/igraph-Coloring.html#igraph_coloring_greedy_t
> I thought you may be interested in this.

Indeed I am. Thanks for the tip!

d.k.
